export const data = {
  categories: ["Watersports", "Soccer", "Chess", "Running"],
  products: [
    {
      id: 1,
      name: "Kayak",
      category: "Watersports",
      description: "A boat for one person",
      price: 275,
    },
    {
      id: 2,
      name: "Lifejacket",
      category: "Watersports",
      description: "Protective and fashionable",
      price: 4895,
    },
    {
      id: 3,
      name: "Soccer Ball",
      category: "Soccer",
      description: "FIFA-approved size and weight",
      price: 195,
    },
    {
      id: 4,
      name: "Corner Flags",
      category: "Soccer",
      description: "Give your playing field a professional touch",
      price: 3495,
    },
    {
      id: 5,
      name: "Stadium",
      category: "Soccer",
      description: "Flat-packed 35,000-seat stadium",
      price: 7950,
    },
    {
      id: 6,
      name: "Thinking Cap",
      category: "Chess",
      description: "Improve brain efficiency by 75%",
      price: 160,
    },
    {
      id: 7,
      name: "Unsteady Chair",
      category: "Chess",
      description: "Secretly give your opponent a disadvantage",
      price: 2995,
    },
    {
      id: 8,
      name: "Human Chess Board",
      category: "Chess",
      description: "A fun game for the family",
      price: 75,
    },
  ],
};
